apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynt-backend
  namespace: default
  labels:
    app: mynt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynt-backend
  template:
    metadata:
      labels:
        app: mynt-backend
    spec:
      containers:
        - name: mynt-backend
          image: petterdaae/mynt-backend:$COMMIT_SHA1
          ports:
            - containerPort: 80
              name: http
          env:
            - name: GIN_MODE
              value: "release"
            - name: PORT
              value: "80"
            - name: ORIGIN
              value: "https://mynt.daae.dev"
            - name: CALLBACK_URL
              value: "https://api.mynt.daae.dev/auth/callback"
            - name: REDIRECT_TO_FRONTEND
              value: "https://mynt.daae.dev/authenticated/transactions"
            - name: REDIRECT_TO_FRONTEND_SIGNOUT
              value: "https://mynt.daae.dev/"
            - name: COOKIE_DOMAIN
              value: "daae.dev"
            - name: JWT_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: mynt-backend-auth
                  key: signing_secret
            - name: GOOGLE_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mynt-backend-auth
                  key: google_client_id
            - name: GOOGLE_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mynt-backend-auth
                  key: google_client_secret
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: do-database-mynt
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: do-database-mynt
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: do-database-mynt
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: do-database-mynt
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: do-database-mynt
                  key: database
            - name: POSTGRES_SSL
              valueFrom:
                secretKeyRef:
                  name: do-database-mynt
                  key: sslmode
