apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynt
  namespace: default
  labels:
    app: mynt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynt
  template:
    metadata:
      labels:
        app: mynt
    spec:
      containers:
        - name: mynt
          image: petterdaae/mynt:$COMMIT_SHA1
          ports:
            - containerPort: 80
              name: http
          env:
            - name: GIN_MODE
              value: 'release'
            - name: PORT
              value: '80'
            - name: ORIGIN
              value: 'https://mynt.daae.dev'
            - name: AUTH0_API_IDENTIFIER
              value: 'mynt-production'
            - name: AUTH0_API_DOMAIN
              value: 'https://dev-sjffsr1q.us.auth0.com/'
            - name: POSTGRES_HOST
              valueFrom:
                  secretKeyRef:
                    name: do-database-mynt
                    key: host
            - name: POSTGRES_PORT
              valueFrom:
                  secretKeyRef:
                    name: do-database-mynt
                    key: port
            - name: POSTGRES_USER
              valueFrom:
                  secretKeyRef:
                    name: do-database-mynt
                    key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: do-database-mynt
                    key: password
            - name: POSTGRES_DB
              valueFrom:
                  secretKeyRef:
                    name: do-database-mynt
                    key: database
            - name: POSTGRES_SSL
              valueFrom:
                  secretKeyRef:
                    name: do-database-mynt
                    key: sslmode
